[package]
name = "Macro-Sand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"
macroquad = "0.4.14"
egui-macroquad = "0.17.3"

[profile.dev]
opt-level = 1
