[package]
name = "macro-sand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
color-eyre = "0.6.2"

[profile.dev]
opt-level = 1 
