[package]
name = "sdl-sand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.36.0"
color-eyre = "0.6.2"
rand = "0.8.5"

[profile.dev]
opt-level = 1 
